Repository 2TEAM-Ideality/be14-final-Ideality-CoreFlow-back, pull requests merged in 2025-05, with the labels that each got.

#7 Setting 멀티테넌시 설정
  .gitignore
  build.gradle
  src/main/java/com/ideality/coreflow/common/tenant/config/DataSourceConfig.java
  src/main/java/com/ideality/coreflow/common/tenant/config/TenantContext.java
  src/main/java/com/ideality/coreflow/common/tenant/config/TenantDataSourceProperties.java
  src/main/java/com/ideality/coreflow/common/tenant/config/TenantDataSourceProvider.java
  src/main/java/com/ideality/coreflow/common/tenant/config/TenantRoutingDataSource.java
  src/main/resources/application.yml
  src/main/resources/secret.properties.example
Labels: ⚙️ Setting

#14 [SETTING] mybatis, redis 의존성 추가
  build.gradle
  src/main/java/com/ideality/coreflow/infra/redis/config/RedisConfig.java
  src/main/java/com/ideality/coreflow/infra/redis/util/RedisUtil.java
Labels: ⚙️ Setting

#16 [REFACTOR] ddl 속성 추가
  src/main/resources/sql/DDL.sql
Labels: 🛠️ Refactor

#22 feat: Comment 엔티티 작성
  src/main/java/com/ideality/coreflow/comment/command/domain/aggregate/Comment.java
  src/main/java/com/ideality/coreflow/comment/command/domain/aggregate/CommentType.java
Labels: ✨ Feature

#26 [SETTING] notification 관련 엔티티 작성 완료
  src/main/java/com/ideality/coreflow/CoreflowBeApplication.java
  src/main/java/com/ideality/coreflow/notification/command/domain/aggregate/Notification.java
  src/main/java/com/ideality/coreflow/notification/command/domain/aggregate/NotificationRecipient.java
Labels: ⚙️ Setting

#24 [SETTING] (payment -> approval 이름 변경) 관련 엔티티 작성 완료
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/Approval.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/ApprovalParticipant.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/DelayApproval.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/DelayReason.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/Role.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/Status.java
  src/main/java/com/ideality/coreflow/approval/domain/aggregate/Type.java
  src/main/java/com/ideality/coreflow/attachment/command/domain/aggregate/FileTargetType.java
  src/main/java/com/ideality/coreflow/notification/command/domain/aggregate/Notification.java
  src/main/resources/sql/DDL.sql
Labels: ⚙️ Setting, 🛠️ Refactor, ✨ Feature

#31 [Refactor] Join관계 표현하던 부분 삭제
  src/main/java/com/ideality/coreflow/comment/command/domain/aggregate/Comment.java
Labels: 🛠️ Refactor

#33 [REFACTOR] user/role 엔티티 추가 안했던 속성 추가
  src/main/java/com/ideality/coreflow/user/command/domain/aggregate/Role.java
  src/main/java/com/ideality/coreflow/user/command/domain/aggregate/RoleType.java
Labels: 🛠️ Refactor

#37 [REFACTOR] DDL 수정(체크 제약조건 추가)
  src/main/java/com/ideality/coreflow/attachment/query/dto/ResponseAttachmentDTO.java
  src/main/java/com/ideality/coreflow/comment/command/domain/aggregate/Comment.java
  src/main/java/com/ideality/coreflow/infra/tenant/config/DataSourceConfig.java
  src/main/java/com/ideality/coreflow/project/command/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/DeptRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ParticipantRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/WorkDeptRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/WorkRepository.java
  src/main/java/com/ideality/coreflow/project/command/dto/DetailRequest.java
  src/main/java/com/ideality/coreflow/project/command/service/DetailService.java
  src/main/resources/sql/Dummy.sql
Labels: 🛠️ Refactor

#40 [FEAT] 공휴일 command 개발 완료
  src/main/java/com/ideality/coreflow/holiday/command/application/controller/HolidayController.java
  src/main/java/com/ideality/coreflow/holiday/command/application/dto/HolidayApiResponse.java
  src/main/java/com/ideality/coreflow/holiday/command/application/service/HolidayService.java
  src/main/java/com/ideality/coreflow/holiday/command/domain/aggregate/HolidayType.java
  src/main/java/com/ideality/coreflow/holiday/command/domain/repository/HolidayRepository.java
  src/main/java/com/ideality/coreflow/infra/tenant/config/DataSourceConfig.java
  src/main/resources/sql/DDL.sql
Labels: ✨ Feature

#42 [REFACTOR] 참여 인원 테이블 및 엔티티 수정 완료
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Participant.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/TargetType.java
  src/main/resources/sql/DDL.sql
Labels: 🛠️ Refactor
