Repository 2TEAM-Ideality/be14-final-Ideality-CoreFlow-back, pull requests merged in 2025-06, with the labels that each got.

#46 [SETTING] 태스크 더미 데이터 완성
  src/main/resources/sql/DummyTask.sql
Labels: ⚙️ Setting

#47 [FEAT] 태스크 생성 완료
  build.gradle
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ResponseTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/TaskParticipantDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/DeptService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/WorkDeptService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkDeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Participant.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Relation.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/WorkDept.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/DeptRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ParticipantRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ProjectRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/TaskRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/WorkDeptRepository.java
  src/main/java/com/ideality/coreflow/project/command/dto/DetailRequest.java
  src/main/java/com/ideality/coreflow/project/command/service/DetailService.java
  src/main/java/com/ideality/coreflow/project/command/service/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/DeptMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/sql/Dummy.sql
  src/main/resources/sql/DummyData.sql
  src/main/resources/sql/dummyData.sql
  src/test/java/com/ideality/coreflow/project/command/application/controller/TaskControllerTest.java
  src/test/java/com/ideality/coreflow/project/query/service/impl/QueryServiceImplTest.java
  src/test/java/com/ideality/coreflow/template/command/application/controller/TemplateCommandControllerTest.java
Labels: ✨ Feature

#52 [REFACTOR][FIX] 버그 수정 및 요구사항 대로 ParticipationDTO 수정 완료
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ParticipantDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ResponseTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ParticipantRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/TaskRepository.java
Labels: 👾 Bug, 🛠️ Refactor

#60 [REFACTOR] 템플릿 조회 - 참여 부서 목록 데이터 구조 변경
  src/main/java/com/ideality/coreflow/template/command/application/controller/TemplateCommandController.java
  src/main/java/com/ideality/coreflow/template/query/controller/TemplateQueryController.java
  src/main/java/com/ideality/coreflow/template/query/dto/DeptDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/ResponseTemplateDetailDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/ResponseTemplateListDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateInfoDTO.java
  src/main/resources/mapper/TemplateMapper.xml
Labels: 🛠️ Refactor

#57 [FEAT] 태스크 상태 수정, 태스크 삭제(소프트 딜리트) 구현 완료
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/WorkDept.java
Labels: ✨ Feature

#66 fix: 되돌리기
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateNodeDataDTO.java
Labels: 👾 Bug

#69 [FEAT] 템플릿 없이 프로젝트 생성 구현 완료
  src/main/java/com/ideality/coreflow/holiday/query/controller/HolidayQueryController.java
  src/main/java/com/ideality/coreflow/holiday/query/dto/HolidayQueryDto.java
  src/main/java/com/ideality/coreflow/holiday/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/holiday/query/mapper/HolidayQueryMapper.java
  src/main/java/com/ideality/coreflow/holiday/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/holiday/query/service/HolidayQueryService.java
  src/main/java/com/ideality/coreflow/holiday/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ParticipantDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ProjectCreateRequest.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Project.java
  src/main/resources/mapper/DeptMapper.xml
  src/main/resources/mapper/HolidayQueryMapper.xml
  src/test/java/com/ideality/coreflow/project/query/service/impl/QueryServiceImplTest.java
Labels: ✨ Feature

#70 [REFACOR] 요구사항에 따른 DTO 및 로직 변경
  src/main/java/com/ideality/coreflow/calendar/command/domain/aggregate/Dept.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/holiday/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/holiday/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/holiday/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkDeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Dept.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/WorkDept.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/DeptRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/resources/mapper/DeptMapper.xml
  src/test/java/com/ideality/coreflow/project/command/application/controller/TaskControllerTest.java
Labels: 🛠️ Refactor

#73 [REFACTOR] 파일 구조 변경된 거 원래대로
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/DeptQueryServiceImpl.java
  src/test/java/com/ideality/coreflow/project/query/service/impl/QueryServiceImplTest.java
Labels: 🛠️ Refactor

#75 [REFACTOR] team-leader list로 수정 완료
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ParticipantMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ParticipantQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ParticipantQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/ParticipantMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#76 [FEAT] 세부일정 조회
  src/main/java/com/ideality/coreflow/common/exception/BaseException.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestDetailDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/DetailService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/query/controller/DeptController.java
  src/main/java/com/ideality/coreflow/project/query/controller/WorkController.java
  src/main/java/com/ideality/coreflow/project/query/dto/DetailDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/ParticipantDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkDetailDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkServieImpl.java
  src/main/java/com/ideality/coreflow/user/query/controller/UserController.java
  src/main/java/com/ideality/coreflow/user/query/dto/UserNameIdDto.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/DeptMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mapper/WorkMapper.xml
  src/main/resources/sql/Dummy.sql
  src/main/resources/sql/DummyData.sql
  src/main/resources/sql/DummyTask.sql
Labels: ✨ Feature

#90 [REFACTOR] 태스크 목록 조회시, 세부 일정 조회 안되게, 완료 수정 삭제 PATCH으로 변경, 딜리트 된것 조회 안되게 설정
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/resources/mapper/TaskMapper.xml
Labels: 🛠️ Refactor

#99 [FEAT] 댓글 작성(일반 댓글, 공지사항 댓글, 대댓글, 첨부 파일 존재 댓글) 구현 완료
  src/main/java/com/ideality/coreflow/attachment/command/application/dto/CreateAttachmentDTO.java
  src/main/java/com/ideality/coreflow/attachment/command/application/service/AttachmentCommandService.java
  src/main/java/com/ideality/coreflow/comment/command/application/controller/CommentController.java
  src/main/java/com/ideality/coreflow/comment/command/application/dto/RequestCommentDTO.java
  src/main/java/com/ideality/coreflow/comment/command/application/service/CommentService.java
  src/main/java/com/ideality/coreflow/comment/command/application/service/facade/CommentFacadeService.java
  src/main/java/com/ideality/coreflow/comment/command/application/service/impl/CommentServiceImpl.java
  src/main/java/com/ideality/coreflow/comment/command/domain/aggregate/Comment.java
  src/main/java/com/ideality/coreflow/comment/command/domain/repository/CommentRepository.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/infra/s3/S3Service.java
  src/main/java/com/ideality/coreflow/infra/s3/UploadFileResult.java
  src/main/java/com/ideality/coreflow/infra/tenant/config/DataSourceConfig.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/template/command/application/service/TemplateCommandFacadeService.java
  src/main/java/com/ideality/coreflow/template/query/service/TemplateQueryFacadeService.java
  src/main/resources/sql/DDL.sql
  src/test/java/com/ideality/coreflow/infra/s3/S3ServiceTests.java
Labels: ✨ Feature

#103 [FEAT] 참여중인 프로젝트 목록 조회 구현 완료
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/DirectorSummaryDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/ProjectSummaryDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
Labels: ✨ Feature

#101 [FEAT] 프로젝트 생성 (템플릿 적용 O) 구현 완료
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
Labels: ✨ Feature

#105 [FEAT] 댓글이나 세부일정에서 쓰일 회원 언급 구현 완료
  src/main/java/com/ideality/coreflow/mention/controller/MentionController.java
  src/main/java/com/ideality/coreflow/mention/dto/RequestMentionDTO.java
  src/main/java/com/ideality/coreflow/mention/service/MentionService.java
  src/main/java/com/ideality/coreflow/mention/service/facade/MentionFacadeService.java
  src/main/java/com/ideality/coreflow/mention/service/impl/MentionServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkServieImpl.java
  src/main/java/com/ideality/coreflow/user/query/dto/UserMentionDTO.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mapper/WorkMapper.xml
  src/main/resources/sql/Dummy.sql
  src/main/resources/sql/DummyData.sql
Labels: ✨ Feature

#107 [FEAT]세부일정 CRUD 구현
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/notification/command/domain/aggregate/Notification.java
  src/main/java/com/ideality/coreflow/notification/command/domain/aggregate/NotificationRecipient.java
  src/main/java/com/ideality/coreflow/notification/query/application/controller/NotificationController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestDetailDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/DetailService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/WorkDeptService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkDeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/WorkDept.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ParticipantRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/WorkDeptRepository.java
  src/main/java/com/ideality/coreflow/project/query/controller/DeptController.java
  src/main/java/com/ideality/coreflow/project/query/dto/DepartmentDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkDetailDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkServieImpl.java
  src/main/resources/mapper/DeptMapper.xml
  src/main/resources/mapper/WorkMapper.xml
  src/main/resources/sql/DummyData.sql
Labels: ✨ Feature

#108 [FEAT] 템플릿 생성 시 요청 데이터 구조 수정 , 프로젝트 템플릿화 - 프로젝트 소요일 정보 반영
  src/main/java/com/ideality/coreflow/attachment/command/application/service/AttachmentCommandService.java
  src/main/java/com/ideality/coreflow/attachment/command/domain/aggregate/Attachment.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/template/command/application/controller/TemplateCommandController.java
  src/main/java/com/ideality/coreflow/template/command/application/dto/RequestCreateTemplateDTO.java
  src/main/java/com/ideality/coreflow/template/command/application/dto/RequestTemplateByProjectDTO.java
  src/main/java/com/ideality/coreflow/template/command/application/dto/RequestUpdateTemplateDTO.java
  src/main/java/com/ideality/coreflow/template/command/application/service/TemplateCommandFacadeService.java
  src/main/java/com/ideality/coreflow/template/command/application/service/TemplateCommandService.java
  src/main/java/com/ideality/coreflow/template/query/controller/TemplateQueryController.java
  src/main/java/com/ideality/coreflow/template/query/dto/BasicTemplateDataDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/NodeDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/NodeDataDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateDetailDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateNodeDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateNodeDataDTO.java
  src/main/java/com/ideality/coreflow/template/query/service/TemplateQueryFacadeService.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/sql/Dummy.sql
  src/test/java/com/ideality/coreflow/template/command/application/controller/TemplateCommandControllerTest.java
  src/test/java/com/ideality/coreflow/template/query/controller/TemplateQueryControllerTest.java
Labels: 🛠️ Refactor, ✨ Feature

#110 [FEAT] 프로젝트 상세 조회
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/ProjectDetailResponseDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/ProjectSummaryDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/UserInfoDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
Labels: ✨ Feature

#120 [Refactor] 로그인, 액세스 토큰 재발급 반환 양식 변경
  src/main/java/com/ideality/coreflow/auth/command/application/dto/ResponseTokenAndUserInfo.java
  src/main/java/com/ideality/coreflow/auth/command/application/service/AuthFacadeService.java
  src/main/java/com/ideality/coreflow/auth/command/application/service/AuthService.java
  src/main/java/com/ideality/coreflow/auth/command/application/service/impl/AuthServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/application/dto/LoginDTO.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserServiceImpl.java
Labels: 🛠️ Refactor

#122 [FEAT] 프로젝트 완료 처리
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ParticipantMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/TaskMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ParticipantQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/TaskQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ParticipantQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
  src/main/resources/mapper/ParticipantMapper.xml
  src/main/resources/mapper/TaskMapper.xml
Labels: ✨ Feature

#125 [Secure] cors 설정 추가
  src/main/java/com/ideality/coreflow/security/config/SecurityConfig.java
Labels: ⚙️ Setting

#126 [FEAT] 프로젝트 상태 변경 기능 구현 완료
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
Labels: ✨ Feature

#130 [Refactor] 결재 요청 시 첨부파일 리스트도 함께 보내도록 수정
  src/main/java/com/ideality/coreflow/approval/command/application/controller/ApprovalController.java
  src/main/java/com/ideality/coreflow/approval/command/application/dto/RequestApproval.java
  src/main/java/com/ideality/coreflow/approval/command/application/service/ApprovalFacadeService.java
Labels: 🛠️ Refactor

#137 [ FEAT] 조직 정보 조회 기능 구현 및 dept 위치 이동
  src/main/java/com/ideality/coreflow/auth/command/application/service/AuthFacadeService.java
  src/main/java/com/ideality/coreflow/org/command/application/controller/OrgController.java
  src/main/java/com/ideality/coreflow/org/command/application/dto/ResponseAllOrgInfo.java
  src/main/java/com/ideality/coreflow/org/command/application/dto/ResponseDept.java
  src/main/java/com/ideality/coreflow/org/command/application/service/DeptService.java
  src/main/java/com/ideality/coreflow/org/command/application/service/OrgFacadeService.java
  src/main/java/com/ideality/coreflow/org/command/application/service/impl/DeptServiceImpl.java
  src/main/java/com/ideality/coreflow/org/command/domain/aggregate/Dept.java
  src/main/java/com/ideality/coreflow/org/command/domain/repository/DeptRepository.java
  src/main/java/com/ideality/coreflow/org/query/controller/DeptController.java
  src/main/java/com/ideality/coreflow/org/query/controller/OrgQueryController.java
  src/main/java/com/ideality/coreflow/org/query/mapper/DeptMapper.java
  src/main/java/com/ideality/coreflow/org/query/service/DeptQueryService.java
  src/main/java/com/ideality/coreflow/org/query/service/OrgQueryFacadeService.java
  src/main/java/com/ideality/coreflow/org/query/service/impl/DeptQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/DeptService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/resources/mapper/DeptMapper.xml
  src/test/java/com/ideality/coreflow/project/query/service/impl/QueryServiceImplTest.java
Labels: 🛠️ Refactor, ✨ Feature

#141 [FIX] Pipeline DTO 자료형 수정
  src/main/java/com/ideality/coreflow/project/query/dto/PipelineResponseDTO.java
Labels: 👾 Bug

#143 [FEAT] 진척률 및 경과율 계산 기능 구현 완료
  src/main/java/com/ideality/coreflow/comment/command/application/service/facade/CommentFacadeService.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/holiday/query/mapper/HolidayQueryMapper.java
  src/main/java/com/ideality/coreflow/holiday/query/service/HolidayQueryService.java
  src/main/java/com/ideality/coreflow/mention/service/facade/MentionFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ProjectService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/WorkService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Project.java
  src/main/java/com/ideality/coreflow/project/query/controller/WorkController.java
  src/main/java/com/ideality/coreflow/project/query/dto/TaskProgressDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/TaskMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/TaskQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkQueryServiceImpl.java
  src/main/resources/mapper/HolidayQueryMapper.xml
  src/main/resources/mapper/TaskMapper.xml
  src/main/resources/mapper/WorkMapper.xml
Labels: ✨ Feature

#146 [FEAT] 프로젝트 팀장, 팀원 초대
  src/main/java/com/ideality/coreflow/comment/command/application/service/facade/CommentFacadeService.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/notification/command/application/service/NotificationRecipientsService.java
  src/main/java/com/ideality/coreflow/notification/command/application/service/NotificationService.java
  src/main/java/com/ideality/coreflow/notification/command/application/service/impl/NotificationRecipientsServiceImpl.java
  src/main/java/com/ideality/coreflow/notification/command/application/service/impl/NotificationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestInviteUserDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/ResponseInvitableUserDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ParticipantMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ParticipantQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ParticipantQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserOfRoleService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserOfRoleServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserServiceImpl.java
  src/main/java/com/ideality/coreflow/user/query/dto/AllUserDTO.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/ParticipantMapper.xml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/sql/DummyData.sql
Labels: ✨ Feature

#147 [FEAT] 프로젝트 참여자 구현 완료
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/DepartmentLeaderDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/ParticipantDepartmentDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/ResponseParticipantDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ParticipantMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ParticipantQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ParticipantQueryServiceImpl.java
  src/main/resources/mapper/ParticipantMapper.xml
Labels: ✨ Feature

#153 [REFACTOR] relation-create 수정 완료
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestModifyTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
Labels: 🛠️ Refactor

#157 [FEAT] 태스크 지연 전파
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/DelayNodeDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/java/com/ideality/coreflow/project/query/mapper/RelationMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/RelationQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/RelationQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkQueryServiceImpl.java
  src/main/resources/mapper/RelationMapper.xml
  src/main/resources/mapper/WorkMapper.xml
Labels: ✨ Feature

#159 [FIX] 충돌 해결 및 기타 버그 수정
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
Labels: 👾 Bug

#175 [REFACTOR] 리프레시 토큰 쿠키 방식으로 변경
  src/main/java/com/ideality/coreflow/auth/command/application/controller/AuthController.java
  src/main/java/com/ideality/coreflow/auth/command/application/dto/ResponseTokenAndUserInfo.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/security/jwt/JwtUtil.java
Labels: 🛠️ Refactor

#177 [FIX] 프로젝트별 태스크 조회 부분 파라미터 수정
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/PdfServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/controller/TaskQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/DeptWorkDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/RequestDeptDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/security/config/SecurityConfig.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/WorkMapper.xml
  src/main/resources/templates/report.html
Labels: 👾 Bug

#181 feat: 파이프라인 조회에 warning 추가
  src/main/java/com/ideality/coreflow/project/query/dto/NodeDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/WorkMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/WorkQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/WorkQueryServiceImpl.java
  src/main/resources/mapper/WorkMapper.xml
Labels: ✨ Feature

#182 [REFACTOR] 결재 상세 조회 반환 값 수정
  src/main/java/com/ideality/coreflow/approval/command/application/service/impl/ApprovalServiceImpl.java
  src/main/java/com/ideality/coreflow/approval/query/dto/ApprovalDetailsDTO.java
  src/main/java/com/ideality/coreflow/approval/query/dto/ApprovalParticipantDTO.java
  src/main/java/com/ideality/coreflow/approval/query/dto/ResponseApprovalDetails.java
  src/main/java/com/ideality/coreflow/approval/query/service/ApprovalQueryFacadeService.java
  src/main/java/com/ideality/coreflow/auth/command/application/controller/AuthController.java
  src/main/java/com/ideality/coreflow/auth/command/application/service/AuthFacadeService.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/security/config/SecurityConfig.java
  src/main/java/com/ideality/coreflow/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ideality/coreflow/tenant/command/application/controller/TenantController.java
  src/main/java/com/ideality/coreflow/tenant/command/application/dto/RequestCreateTenant.java
  src/main/java/com/ideality/coreflow/tenant/command/application/dto/ResponseInitialAdmin.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantFacadeService.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantService.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantServiceImpl.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/impl/TenantServiceImpl.java
  src/main/java/com/ideality/coreflow/tenant/command/domain/aggregate/ErpMaster.java
  src/main/java/com/ideality/coreflow/tenant/command/domain/repository/TenantRepository.java
  src/main/java/com/ideality/coreflow/tenant/query/controller/TenantQueryController.java
  src/main/java/com/ideality/coreflow/tenant/query/dto/ResponseSchemaInfo.java
  src/main/java/com/ideality/coreflow/tenant/query/mapper/TenantMapper.java
  src/main/java/com/ideality/coreflow/tenant/query/service/TenantQueryFacadeService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/domain/aggregate/User.java
  src/main/resources/mapper/ApprovalMapper.xml
  src/main/resources/mapper/TenantMapper.xml
  src/main/resources/sql/DDL.sql
  src/main/resources/sql/master.sql
Labels: 🛠️ Refactor

#191 [FEAT] 프로젝트 참여인원 목록 조회
  src/main/java/com/ideality/coreflow/project/query/dto/UserInfoDTO.java
  src/main/resources/mapper/ParticipantMapper.xml
Labels: ✨ Feature

#192 [FEAT] 태스크 상세 수정 구현 완료
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestModifyTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/WorkDeptService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkDeptServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/WorkDeptRepository.java
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/SelectTaskDTO.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
  src/main/resources/mapper/RelationMapper.xml
  src/main/resources/mapper/TaskMapper.xml
Labels: ✨ Feature

#194 [FEAT] 세부일정용 조회로직추가
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestDetailDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/query/dto/DetailDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkDetailDTO.java
  src/main/java/com/ideality/coreflow/user/query/controller/UserQueryController.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mapper/WorkMapper.xml
Labels: ✨ Feature

#195 [FEAT] 메인 홈에서 필요한 오늘의 부서 일증 기능 추가
  src/main/java/com/ideality/coreflow/approval/query/dto/ProjectApprovalDTO.java
  src/main/java/com/ideality/coreflow/calendar/query/controller/CalendarQueryController.java
  src/main/java/com/ideality/coreflow/calendar/query/dto/TodayScheduleDTO.java
  src/main/java/com/ideality/coreflow/calendar/query/service/CalendarQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/controller/TaskQueryController.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/resources/mapper/ApprovalMapper.xml
  src/main/resources/sql/DummyForReport.sql
  src/main/resources/sql/DummyPipe.sql
Labels: ✨ Feature

#197 [REFACTOR] 스키마 생성 리팩토링
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantFacadeService.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/impl/TenantServiceImpl.java
  src/main/resources/sql/DDL.sql
Labels: 🛠️ Refactor

#198 [FEAT] 마감 임박 태스크, 세부일정
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/TaskSummaryResponse.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkDueTodayDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkSummaryDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ProjectMapper.java
  src/main/java/com/ideality/coreflow/project/query/mapper/TaskMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ProjectQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/TaskQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ProjectQueryServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/TaskMapper.xml
Labels: ✨ Feature

#207 [FEAT] 태스크 관계만 수정 구현 완료 + 다시 DEPLOY로 변경
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestRelationUpdateDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/sql/DummyTask.sql
Labels: 🌎 Deploy

#209 [FEAT]태스크 상세조회 시 '마감 임박 세부 일정 갯수'를 리턴하는 기능 추가
  src/main/java/com/ideality/coreflow/project/query/dto/ResponseTaskInfoDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/SelectTaskDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/TaskMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/TaskQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
  src/main/resources/mapper/TaskMapper.xml
Labels: 🛠️ Refactor, ✨ Feature

#211 [FEAT] 마감 임박 세부일정 정보에 부모태스크 정보 추가
  src/main/java/com/ideality/coreflow/project/query/dto/WorkDueTodayDTO.java
  src/main/java/com/ideality/coreflow/project/query/dto/WorkSummaryDTO.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/resources/mapper/TaskMapper.xml
Labels: ✨ Feature

#213 [REFACTOR] 프로젝트, 테넌트 도메인 리팩토링
  src/main/java/com/ideality/coreflow/approval/command/application/service/ApprovalFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/ProjectCreateRequest.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/template/query/dto/NodeDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/NodeDataDTO.java
  src/main/java/com/ideality/coreflow/template/query/dto/TemplateDataDTO.java
  src/main/java/com/ideality/coreflow/tenant/command/application/controller/TenantController.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantFacadeService.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/TenantService.java
  src/main/java/com/ideality/coreflow/tenant/command/application/service/impl/TenantServiceImpl.java
  src/main/java/com/ideality/coreflow/tenant/command/domain/repository/TenantRepository.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/domain/repository/UserRepository.java
  src/main/java/com/ideality/coreflow/user/query/mapper/UserMapper.java
  src/main/java/com/ideality/coreflow/user/query/service/UserQueryService.java
  src/main/java/com/ideality/coreflow/user/query/service/impl/UserQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/TenantMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/sql/master.sql
Labels: 🛠️ Refactor, ✨ Feature

#212 [REFACTOR] 프로젝트 목록 조회 순서 변경
  src/main/resources/mapper/ProjectMapper.xml
Labels: 🛠️ Refactor

#215 [FEAT] 참여자 추가 기능
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#224 [REFACTOR] approvalHistory용 조회 데이터 추가
  src/main/java/com/ideality/coreflow/approval/query/dto/ResponsePreviewApproval.java
  src/main/resources/mapper/ApprovalMapper.xml
Labels: 🛠️ Refactor

#227 [REFACTOR] 프로필 사진 S3 연동 완료 + S3 파일명 저장 변경
  build.gradle
  src/main/java/com/ideality/coreflow/admin/command/application/controller/AdminController.java
  src/main/java/com/ideality/coreflow/admin/command/application/dto/RequestUserUpdateByAdmin.java
  src/main/java/com/ideality/coreflow/admin/command/application/service/AdminFacadeService.java
  src/main/java/com/ideality/coreflow/infra/s3/S3Service.java
  src/main/java/com/ideality/coreflow/user/command/application/controller/UserController.java
  src/main/java/com/ideality/coreflow/user/command/application/dto/RequestUpdateProfile.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserFacadeService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/UserService.java
  src/main/java/com/ideality/coreflow/user/command/application/service/impl/UserServiceImpl.java
  src/main/java/com/ideality/coreflow/user/command/domain/aggregate/User.java
  src/main/java/com/ideality/coreflow/user/query/controller/UserQueryController.java
Labels: 🛠️ Refactor

#233 [FEAT] 태스크 경고 상태를 위한 상세일정 수정 DTO 변경
  src/main/java/com/ideality/coreflow/project/command/application/controller/DetailController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestDetailDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
Labels: 🛠️ Refactor

#234 [FIX] 프로젝트 실제 시작일 업데이트 수정
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ProjectServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Project.java
Labels: 👾 Bug

#238 [FEAT] 태스크 초대 완성
  src/main/java/com/ideality/coreflow/notification/command/application/service/NotificationService.java
  src/main/java/com/ideality/coreflow/notification/command/application/service/impl/NotificationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/controller/TaskQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/ParticipantUserDTO.java
  src/main/java/com/ideality/coreflow/project/query/mapper/ParticipantMapper.java
  src/main/java/com/ideality/coreflow/project/query/service/ParticipantQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/ParticipantQueryServiceImpl.java
  src/main/resources/mapper/ParticipantMapper.xml
Labels: ✨ Feature

#239 [REFACTOR] 디렉터 예외처리 추가
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
Labels: 🛠️ Refactor

#241 [PDF]
  src/main/java/com/ideality/coreflow/approval/query/dto/ProjectApprovalDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/PdfServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/ProjectQueryController.java
  src/main/java/com/ideality/coreflow/project/query/dto/ProjectDetailResponseDTO.java
  src/main/java/com/ideality/coreflow/security/config/SecurityConfig.java
  src/main/resources/mapper/ApprovalMapper.xml
  src/main/resources/templates/report.html
Labels: 🛠️ Refactor

#242 [FIX] 댓글 첨부파일 존재 여부 분기문 추가(닫지 마세요 수정중)
  src/main/java/com/ideality/coreflow/approval/command/application/service/ApprovalFacadeService.java
  src/main/java/com/ideality/coreflow/comment/query/service/facade/CommentQueryFacadeService.java
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestDeleteParticipant.java
  src/main/java/com/ideality/coreflow/project/command/application/service/ParticipantService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/ParticipantServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/TargetType.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/ParticipantRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/service/WorkDomainService.java
  src/main/java/com/ideality/coreflow/project/command/domain/service/WorkDomainServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/WorkController.java
  src/main/resources/mapper/ProjectMapper.xml
Labels: 👾 Bug

#245 [REFACTOR] 슬랙타임 계산 로직 추가
  src/main/java/com/ideality/coreflow/holiday/command/application/service/HolidayService.java
  src/main/java/com/ideality/coreflow/holiday/command/domain/repository/HolidayRepository.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/ProjectController.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/EdgeInfoDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/dto/RequestTaskDTO.java
  src/main/java/com/ideality/coreflow/project/command/application/service/RelationService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/RelationServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/java/com/ideality/coreflow/project/command/domain/repository/RelationRepository.java
  src/main/java/com/ideality/coreflow/project/command/domain/service/DelayDomainServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/service/WorkDomainService.java
  src/main/java/com/ideality/coreflow/project/command/domain/service/WorkDomainServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/dto/ResponseTaskDTO.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
Labels: 🛠️ Refactor, ✨ Feature

#244 [FEAT] 테스트 코드 작성
  src/test/java/com/ideality/coreflow/template/command/application/service/TemplateCommandServiceTest.java
Labels: ✨ Feature

#246 [REFACTOR] 지연 예상일 계산 로직
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/DetailServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/controller/TaskQueryController.java
  src/main/java/com/ideality/coreflow/project/query/service/TaskQueryService.java
  src/main/java/com/ideality/coreflow/project/query/service/facade/ProjectQueryFacadeService.java
  src/main/java/com/ideality/coreflow/project/query/service/impl/TaskQueryServiceImpl.java
Labels: 🛠️ Refactor, ✨ Feature

#247 [REFACTOR] 태스크 관련 삭제, 중단 추가
  src/main/java/com/ideality/coreflow/common/exception/ErrorCode.java
  src/main/java/com/ideality/coreflow/project/command/application/controller/TaskController.java
  src/main/java/com/ideality/coreflow/project/command/application/service/TaskService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/facade/ProjectFacadeService.java
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/TaskServiceImpl.java
  src/main/java/com/ideality/coreflow/project/command/domain/aggregate/Work.java
  src/main/resources/mapper/TaskMapper.xml
  src/test/java/com/ideality/coreflow/infra/s3/S3ServiceTests.java
  src/test/java/com/ideality/coreflow/project/command/application/service/impl/PdfServiceTest.java
Labels: 🛠️ Refactor

#250 [REFACTOR] 지연 결재 시 변경 예상 마감일 계산을 위한 데이터 반환
  src/main/java/com/ideality/coreflow/project/command/application/service/impl/WorkServiceImpl.java
  src/main/java/com/ideality/coreflow/project/query/dto/TaskPreviewDTO.java
Labels: 🛠️ Refactor

#253 refactor 프로젝트 삭제 취소건 조회 x
  src/main/resources/mapper/ProjectMapper.xml
Labels: 🛠️ Refactor

#254 [REFACTOR] 프로젝트 리스트 상태에 맞는 날짜 정보로 수정.
  src/main/resources/mapper/ProjectMapper.xml
Labels: 🛠️ Refactor
